services:
  db:
    image: postgres:16
    container_name: ledger_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: bank_ledger
      TZ: UTC
      PGTZ: UTC
    command: ["postgres", "-c", "timezone=UTC"] # Force UTC at the engine level
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: